
twitter_speak = {'af':'as fuck',
                'rn':'right now',
                'lol':'laugh out loud',
                'lmao':'laughing my ass off',
                'bruh':'brother',
                'bro':'brother',
                'rly':'really',
                '(:':'happy',
                ':(':'sad',
                'smh':'shaking my head',
                'smdh':'shaking my damn head',
                'guac':'guacamole',
                'ok': 'okay',
                'lit':'awesome',
                'dope':'awesome',
                'chill': 'awesome',
                'imo':'in my opinion',
                'dm':'message',
                'fyi':'for your information',
                'fym':'free your mind',
                'ur':'you are',
                'omg':'oh my god',
                'finna':'going to',
                }
